# Generated by Django 5.1.2 on 2024-11-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.CharField(default='Cricket, Kabaddi', max_length=200),
        ),
    ]
