# Generated by Django 5.1.2 on 2024-11-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0002_alter_person_chemistry_alter_person_maths_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Person1',
        ),
    ]
